name: Community Scan flair (public baseline)

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    name: Community scan flair/ner-english-ontonotes (public)
    steps:
      - uses: actions/checkout@v3

      - name: Scan
        uses: hiddenlayerai/hiddenlayer-model-scan-github-action@v1.0.5
        with:
          model_path: flair/ner-english-ontonotes
          model_version: main
          community_scan: HUGGING_FACE
        env:
          HL_CLIENT_ID: ${{ secrets.HL_CLIENT_ID }}
          HL_CLIENT_SECRET: ${{ secrets.HL_CLIENT_SECRET }}
